# This is the configuration used to check the rubocop source code.
# Check out: https://github.com/bbatsov/rubocop

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'bin/**/*'
    - 'bundler_stubs/**/*'
    - 'config/locales/plurals.rb'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  Max: 10

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  AlignWith: variable
