language: ruby
script:
  - 'bundle exec rake test:prepare'
  - 'TRAVIS=1 CODECLIMATE_REPO_TOKEN=0d4c6a0f16f910a02bbb2cf8ce47e52d7c5f95b8bd6366d9b3a1a113a4e52486 bundle exec rspec'
rvm:
  - 2.1.1
addons:
  postgresql: '9.3'
before_script:
  - psql -c 'create database va_db_tst;' -U postgres
  - cp config/database.yml.travis config/database.yml
