language: ruby
script:
  - 'bundle exec rake test:prepare'
  - 'TRAVIS=1 CODECLIMATE_REPO_TOKEN=783e4ac8cc44be68f2be2932fb13e2805e1f21b4541d689c9c7fe12bfb2373fb bundle exec rspec -s 63423'
rvm:
  - 2.1.5
addons:
  postgresql: '9.3'
before_script:
  - psql -c 'create database va_db_tst;' -U postgres
  - cp config/database.yml.travis config/database.yml
