version: '2'

volumes:
  redis-prod:
    external: false
  public-prod:
    external: false
  bundle-prod:
    external: false
  uploads-prod:
    external: false
  postgres-prod:
    external: false

services:
  postgres:
    image:          mpugach/postgres_ua:9.5
    container_name: postgres
    volumes:
      - postgres-prod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:    va_db
      POSTGRES_USER:  postgres

  redis:
    image:          redis:3.2.4-alpine
    container_name: redis
    volumes:
      - redis-prod:/data

  application:
    image:          mpugach/akadem_students_prod:latest
    command:        bundle exec puma -C config/puma.rb
    env_file:       ./.ruby-env
    container_name: application
    expose:
      - '3000'
    volumes:
      - public-prod:/app/public
      - bundle-prod:/usr/local/bundle
      - uploads-prod:/app/uploads
    depends_on:
      - redis
      - postgres
    environment:
      RAILS_ENV:            production
      RAILS_LOG_TO_STDOUT:  1

  nginx:
    image:          mpugach/akadem_students_nginx:latest
    command:        nginx -g 'daemon off;'
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - public-prod:/assets/public:ro
      - uploads-prod:/assets/uploads:ro
    depends_on:
      - application

