version: '2'
services:
  postgres:
    image:          mpugach/postgres_ua:9.5
    container_name: postgres
    volumes:
      - /home/docker/ved_akadem_students:/data
    environment:
      POSTGRES_DB:    va_db
      POSTGRES_USER:  postgres
  redis:
    image:          redis:3.2.4-alpine
    container_name: redis
  application:
    image:          mpugach/akadem_students_base:201610160
    entrypoint:     /app/bin/start_rails_dev.sh
    container_name: application
    ports:
      - '3000:3000'
    volumes:
      - /home/docker/ved_akadem_students:/app
    depends_on:
      - redis
      - postgres
