default: &default
  :concurrency: 10
  :verbose: true
  :queues:
    - urgent
    - default
    - low
    - mailers

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  :pidfile: ./tmp/sidekiq.pid
